packages:
    - examples/*

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
    # Renovate security update: nuxt@4.4.7
    - nuxt@4.4.7
    # Renovate security update: vite@8.0.16
    - vite@8.0.16
    # Renovate security update: astro@6.4.6
    - astro@6.4.6
    # Renovate security update: http-proxy-middleware@3.0.7
    - http-proxy-middleware@3.0.7
    # Renovate security update: esbuild@0.28.1
    - esbuild@0.28.1
    # Renovate security update: @angular/core@19.2.25
    - "@angular/core@19.2.25"
    # Renovate security update: @angular/core@21.2.17
    - "@angular/core@21.2.17"
    # Renovate security update: @angular/common@19.2.25
    - "@angular/common@19.2.25"
    # Renovate security update: @angular/compiler@19.2.25
    - "@angular/compiler@19.2.25"
