import { parse } from "node:path";

import type { EmittedFile } from "../../types";

/**
 * Provided a list of EmittedFile descriptors and a search query, returns the
 * single EmittedFile whose name most closely matches the search query.
 */
const findEmittedFile = (emittedFiles: EmittedFile[], searchFilePath: string): EmittedFile | undefined => {
    // Extract the name (sans extension) generated by `favicons` for the search
    // file. For example: 'apple-touch-startup-image.png'
    const faviconsFileName = parse(searchFilePath).name;

    return emittedFiles.find((file) => faviconsFileName === parse(file.name).name);
};

export default findEmittedFile;
