name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yml@0a43f1373be806fe25f390a7119dfd7292c6850f" # main
        with:
            target-repo: "anolilab/unplugin-favicons"
