name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yml@1641a17797e6e1dc3eaf9b462c3c0dae91ab071d" # v20.2.12
        with:
            target-repo: "anolilab/unplugin-favicons"
