name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yml@7d86f5451bc5e671c0910428ee71e79ebadaf94e" # main
        with:
            target-repo: "anolilab/unplugin-favicons"
