name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch: # yamllint disable-line rule:empty-values

permissions:
    contents: "read"
    discussions: "write"
    issues: "write"
    pull-requests: "write"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@1641a17797e6e1dc3eaf9b462c3c0dae91ab071d" # v20.2.12
        with:
            target-repo: "anolilab/unplugin-favicons"
