name: "Require 'Allow Edits'"

on: ["pull_request_target", "merge_group"] # yamllint disable-line rule:truthy

permissions:
    contents: "read"

jobs:
    check_allow_edits:
        permissions:
            pull-requests: "read" # for ljharb/require-allow-edits to check 'allow edits' on PR

        name: "Require “Allow Edits”"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142" # v2.7.0
              with:
                  egress-policy: "audit"

            - uses: "ljharb/require-allow-edits@13f90bc8cc5de000f2b44a0e2c3a11d108e8cd9f" # main
              with:
                  pull_number: "${{ github.event.pull_request.number }}"
