name: "Scorecards supply-chain security"
on: # yamllint disable-line rule:truthy
    branch_protection_rule: ~
    schedule:
        - cron: "37 14 * * 6"
    push:
        branches: ["main", "master", "alpha", "beta"]
permissions: {}
jobs:
    scorecards:
        permissions:
            security-events: "write"
            id-token: "write"
            actions: "read"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/scorecards.yml@9663c7c69bc7dac1a294407a44c30f68977303bb" # main
        with:
            branch: "main"
            publish_results: true
