# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Release"

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - "([0-9])?(.{+([0-9]),x}).x"
            - "main"
            - "next"
            - "next-major"
            - "alpha"
            - "beta"

permissions:
    contents: "read" # for checkout

jobs:
    build:
        name: "Build Package"
        if: "github.repository == 'anolilab/unplugin-favicons'"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350" # v2.10.3
              with:
                  egress-policy: "audit"

            - name: "Wait for tests to succeed"
              uses: "lewagon/wait-on-check-action@595dabb3acf442d47e29c9ec9ba44db0c6bdd18f" # v1.3.3
              timeout-minutes: 20
              with:
                  ref: "${{ github.event.pull_request.head.sha || github.sha }}"
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  wait-interval: 60 # seconds
                  running-workflow-name: "Build Package" # wait for all other checks to complete
                  allowed-conclusions: "success,neutral,skipped" # all other checks must pass, being skipped or cancelled is not sufficient

            - name: "Git checkout"
              uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
              with:
                  fetch-depth: 0
                  persist-credentials: false
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Setup resources and environment"
              id: "setup"
              uses: "anolilab/workflows/step/setup@main"
              with:
                  node-version: "18.x"
                  cache-prefix: "semantic-release"

            - name: "Build Production"
              run: "pnpm run build:prod"

            - name: "test and coverage"
              run: "pnpm run test:coverage"
            # @TODO: Enable it later
            #            - name: "Upload code coverage to codecov"
            #              uses: "anolilab/workflows/step/codecov@main"
            #              with:
            #                  run-lint: "false"
            #                  codecov-token: "${{ secrets.CODECOV_TOKEN }}"

            - name: "Publish Build Artifacts"
              uses: "actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08" # v4.6.0
              with:
                  name: "unplugin-favicons-dist"
                  path: "${{ github.workspace }}/dist"

    semantic-release:
        name: "Semantic Release"
        needs: ["build"]
        runs-on: "ubuntu-latest"
        permissions:
            contents: "write" # to be able to publish a GitHub release
            issues: "write" # to be able to comment on released issues
            pull-requests: "write" # to be able to comment on released pull requests
            id-token: "write" # to enable use of OIDC for npm provenance

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350" # v2.10.3
              with:
                  egress-policy: "audit"

            - name: "Git checkout"
              uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
              with:
                  fetch-depth: 0
                  persist-credentials: false
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Setup resources and environment"
              id: "setup"
              uses: "anolilab/workflows/step/setup@main"
              with:
                  node-version: "20.x"
                  cache-prefix: "semantic-release"

            - name: "Download Build Artifacts"
              uses: "actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16" # v4.1.8
              with:
                  name: "unplugin-favicons-dist"
                  path: "${{ github.workspace }}/dist"

            - name: "Semantic Release"
              if: "success()"
              env:
                  GITHUB_TOKEN: "${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}"
                  NPM_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"
                  GIT_AUTHOR_NAME: "github-actions-shell"
                  GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
                  GIT_COMMITTER_NAME: "github-actions-shell"
                  GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
              run: "pnpm exec semantic-release"
