# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Release"

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - "([0-9])?(.{+([0-9]),x}).x"
            - "main"
            - "next"
            - "next-major"
            - "alpha"
            - "beta"

permissions:
    contents: "read" # for checkout

jobs:
    semantic-release:
        name: "Semantic Release"
        runs-on: "ubuntu-latest"
        permissions:
            contents: "write" # to be able to publish a GitHub release
            issues: "write" # to be able to comment on released issues
            pull-requests: "write" # to be able to comment on released pull requests
            id-token: "write" # to enable use of OIDC for npm provenance

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c" # v2.9.0
              with:
                  egress-policy: "audit"

            - name: "Wait for tests to succeed"
              uses: "lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc" # v1.3.4
              timeout-minutes: 20
              with:
                  ref: "${{ github.event.pull_request.head.sha || github.sha }}"
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  wait-interval: 60 # seconds
                  running-workflow-name: "Semantic Release" # wait for all other checks to complete
                  allowed-conclusions: "success,skipped" # all other checks must pass, being skipped or cancelled is not sufficient

            - name: "Git checkout"
              uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
              with:
                  fetch-depth: 0
                  persist-credentials: false
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: "pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d" # v3.0.0
              with:
                  run_install: false

            - name: "Use Node.js 20.6.1"
              uses: "actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b" # v4.0.3
              with:
                  node-version: "20.6.1"
                  cache: "pnpm"

            # @see: npm install -g npm@latest is necessary to make provenance available. More info: https://docs.npmjs.com/generating-provenance-statements
            - name: "Upgrade npm to latest version"
              run: "npm install --global npm@9.6.x"
              env:
                  SKIP_CHECK: "true"

            - name: "Check npm version"
              run: "npm -v"
              env:
                  SKIP_CHECK: "true"

            - name: "Install packages"
              run: "pnpm install --frozen-lockfile"

            - name: "Verify the integrity of provenance attestations and registry signatures for installed dependencies"
              run: "pnpm audit signatures"

            - name: "npm v8.5+ requires workspaces-update to be set to false"
              run: "echo 'workspaces-update=false' >> .npmrc"

            - name: "Build package"
              run: "pnpm run build:prod"

            - name: "Validate package.json"
              run: "pnpm run validate:package"

            - name: "Semantic Release"
              if: "success()"
              env:
                  GITHUB_TOKEN: "${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}"
                  NPM_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"
                  GIT_AUTHOR_NAME: "github-actions-shell"
                  GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
                  GIT_COMMITTER_NAME: "github-actions-shell"
                  GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
              run: "pnpm exec semantic-release"

    pnpm-lock-update:
        needs: "semantic-release"
        name: "pnpm-lock.yaml update"
        runs-on: "ubuntu-latest"
        permissions:
            contents: "write" # to be able to publish
        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c" # v2.9.0
              with:
                  egress-policy: "audit"

            - name: "Git checkout"
              uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: "pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d" # v3.0.0

            - name: "Use Node.js 20.6.1"
              uses: "actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b" # v4.0.3
              with:
                  node-version: "20.6.1"

            - name: "Update pnpm lock"
              run: "pnpm install --no-frozen-lockfile"

            - name: "Commit modified files"
              uses: "stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842" # v5.0.1
              with:
                  commit_message: "chore: updated pnpm-lock.yaml"
                  commit_author: "prisis <d.bannert@anolilab.de>"
                  commit_user_email: "d.bannert@anolilab.de"
                  commit_user_name: "prisis"
                  branch: "${{ github.head_ref }}"
